// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__NavbarController from "./admin/navbar_controller"
application.register("admin--navbar", Admin__NavbarController)

import Admin__ProgressBarController from "./admin/progress_bar_controller"
application.register("admin--progress-bar", Admin__ProgressBarController)

import Admin__SidebarController from "./admin/sidebar_controller"
application.register("admin--sidebar", Admin__SidebarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
