default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: qwer4321
  host: db

development:
  <<: *default
  database: learning_management_system_development

test:
  <<: *default
  database: learning_management_system_test

production:
  <<: *default
  database: learning_management_system_production
  username: app
  password: <%= ENV["LEARNING_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>